### PR TITLE
Fix ENOENT error when spawning the ".bin/cdk" binary wrapper

### PR DESCRIPTION
**Pull request by octogonz**
### Problem

The `getCdkBinPath()` function tries to guess the file path for the `.bin/cdk` binary wrapper from the `aws-cdk` NPM package, however this heuristic expects a very specific `node_modules` layout.  It will fail in nontrivial installation scenarios.

### Details

In my case, `aws-cdk` was installed in a PNPM workspace, resulting in this error:

```
Error: spawn C:\Git\example-monorepo\common\temp\node_modules\.pnpm\aws-cdk@2.15.0\node_modules\.bin\cdk ENOENT
    at notFoundError (C:\Git\example-monorepo\common\temp\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:6:26)
    at verifyENOENT (C:\Git\example-monorepo\common\temp\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:40:16)
    at ChildProcess.cp.emit (C:\Git\example-monorepo\common\temp\node_modules\.pnpm\cross-spawn@7.0.3\node_modules\cross-spawn\lib\enoent.js:27:25)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12) {
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn C:\\Git\\example-monorepo\\common\\temp\\node_modules\\.pnpm\\aws-cdk@2.15.0\\node_modules\\.bin\\cdk',
  path: 'C:\\Git\\example-monorepo\\common\\temp\\node_modules\\.pnpm\\aws-cdk@2.15.0\\node_modules\\.bin\\cdk',
  spawnargs: [
    'synth',
    '--no-version-reporting',
```

### Proposed fix

If `aws-cdk` is installed as an indirect dependency, the package manager is not going to create the binary wrapper at all.  A more robust solution is to probe for `aws-sdk/bin/cdk.js` and invoke that directly using `node.exe`.  

CC  @frekje-wm

### CODE REVIEW

**Comment by octogonz** [comment]
@fwang Some validation rules are failing, however I don't have permissions to view the Netlify build logs to see the error message. How to proceed?

**Comment by octogonz** [comment]
This appears to be a recent regression caused by PR #1548

**Comment by otterDeveloper** [comment]
Wow I just ran into exactly the same problem. I was testing whether SST would work with yarn 3 Pnp and I get the same problem

**Comment by fwang** [comment]
Released in v0.69.6 and v1.0.0-beta.20

**Pull request merged**
