### PR TITLE
Improving docs for bundling props

### PR DESCRIPTION
**Pull request by jayair**

### CODE REVIEW

**Comment by pabacham** [comment]
My second Stack accepts following args 
`constructor(scope: sst.App, id: string, props?: sst.StackProps)`

But seems like sst.StackProps does not accept api prop, it throws a TS error 

Argument of type '{ api: sst.Api; }' is not assignable to parameter of type 'StackProps'.
  Object literal may only specify known properties, and 'api' does not exist in type 'StackProps'.ts(2345)

**Comment by Rohithgilla12** [comment]
@pabacham hey I am getting this too, how did you solve it?

**Comment by fwang** [comment]
Note that you don't have to pass it through `StackProps`. You can pass it directly to the constructor. Here's an example in TypeScript - https://docs.serverless-stack.com/advanced/cross-stack-references

**Comment by Rohithgilla12** [comment]
@fwang Something like this
```
interface StorageStackProps extends sst.StackProps {
  table: sst.Table;
}

```

**Comment by fwang** [comment]
Yup, right on!

**Pull request merged**
